//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.05.22 at 11:15:50 PM EDT 
//


package com.panther.xmlhandlr.xjcoutput;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ProjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProjectType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="projCode" type="{http://xyz.com/thisisEx/emp}PrjCodeType"/&gt;
 *         &lt;element name="projUnit" type="{http://xyz.com/thisisEx/emp}UintType"/&gt;
 *         &lt;element name="projManager" type="{http://xyz.com/thisisEx/emp}EmpIdType"/&gt;
 *         &lt;element name="projStartDate" type="{http://xyz.com/thisisEx/emp}DateType"/&gt;
 *         &lt;element name="projEndDate" type="{http://xyz.com/thisisEx/emp}DateType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProjectType", propOrder = {
    "projCode",
    "projUnit",
    "projManager",
    "projStartDate",
    "projEndDate"
})
public class ProjectType {

    @XmlElement(required = true)
    protected String projCode;
    @XmlElement(required = true)
    protected String projUnit;
    @XmlElement(required = true)
    protected String projManager;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar projStartDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar projEndDate;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;

    /**
     * Gets the value of the projCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjCode() {
        return projCode;
    }

    /**
     * Sets the value of the projCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjCode(String value) {
        this.projCode = value;
    }

    /**
     * Gets the value of the projUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjUnit() {
        return projUnit;
    }

    /**
     * Sets the value of the projUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjUnit(String value) {
        this.projUnit = value;
    }

    /**
     * Gets the value of the projManager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjManager() {
        return projManager;
    }

    /**
     * Sets the value of the projManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjManager(String value) {
        this.projManager = value;
    }

    /**
     * Gets the value of the projStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProjStartDate() {
        return projStartDate;
    }

    /**
     * Sets the value of the projStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProjStartDate(XMLGregorianCalendar value) {
        this.projStartDate = value;
    }

    /**
     * Gets the value of the projEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProjEndDate() {
        return projEndDate;
    }

    /**
     * Sets the value of the projEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProjEndDate(XMLGregorianCalendar value) {
        this.projEndDate = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
