//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.05.22 at 11:15:50 PM EDT 
//


package com.panther.xmlhandlr.xjcoutput;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkSiteType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkSiteType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cubeId" type="{http://xyz.com/thisisEx/emp}CubeIdType"/&gt;
 *         &lt;element name="floorNumber" type="{http://xyz.com/thisisEx/emp}FloorNumType"/&gt;
 *         &lt;element name="bldName" type="{http://xyz.com/thisisEx/emp}STR-25"/&gt;
 *         &lt;element name="cubeMode" type="{http://xyz.com/thisisEx/emp}STR-10" minOccurs="0"/&gt;
 *         &lt;element name="deskNumber" type="{http://xyz.com/thisisEx/emp}PhoneType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkSiteType", propOrder = {
    "cubeId",
    "floorNumber",
    "bldName",
    "cubeMode",
    "deskNumber"
})
public class WorkSiteType {

    @XmlElement(required = true)
    protected String cubeId;
    @XmlElement(required = true)
    protected BigInteger floorNumber;
    @XmlElement(required = true)
    protected String bldName;
    protected String cubeMode;
    @XmlElement(required = true)
    protected String deskNumber;

    /**
     * Gets the value of the cubeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCubeId() {
        return cubeId;
    }

    /**
     * Sets the value of the cubeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCubeId(String value) {
        this.cubeId = value;
    }

    /**
     * Gets the value of the floorNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFloorNumber() {
        return floorNumber;
    }

    /**
     * Sets the value of the floorNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFloorNumber(BigInteger value) {
        this.floorNumber = value;
    }

    /**
     * Gets the value of the bldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBldName() {
        return bldName;
    }

    /**
     * Sets the value of the bldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBldName(String value) {
        this.bldName = value;
    }

    /**
     * Gets the value of the cubeMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCubeMode() {
        return cubeMode;
    }

    /**
     * Sets the value of the cubeMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCubeMode(String value) {
        this.cubeMode = value;
    }

    /**
     * Gets the value of the deskNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeskNumber() {
        return deskNumber;
    }

    /**
     * Sets the value of the deskNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeskNumber(String value) {
        this.deskNumber = value;
    }

}
